# Generated by Django 5.2.10 on 2026-02-08 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationnote',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
            preserve_default=False,
        ),
    ]
