# Generated by Django 5.2.10 on 2026-02-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_consultationnote_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Doctor_name',
            new_name='doctor_name',
        ),
    ]
